// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBli497V7iEymS4uzE2L1vixOZ7eLsk_EE',
    appId: '1:152439228985:web:1cad41af7f75b5651d9be8',
    messagingSenderId: '152439228985',
    projectId: 'thefuture-f7945',
    authDomain: 'thefuture-f7945.firebaseapp.com',
    storageBucket: 'thefuture-f7945.appspot.com',
    measurementId: 'G-TJN5DXR710',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSQP9VxCcg73H0GQwCgzhkNk7YAwXSXFg',
    appId: '1:152439228985:android:db2310d1eb0f5bce1d9be8',
    messagingSenderId: '152439228985',
    projectId: 'thefuture-f7945',
    storageBucket: 'thefuture-f7945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_1G72dP1XPDcdD-f9WsTp2OWvfHITsY',
    appId: '1:152439228985:ios:99f7f71b08ccaa181d9be8',
    messagingSenderId: '152439228985',
    projectId: 'thefuture-f7945',
    storageBucket: 'thefuture-f7945.appspot.com',
    iosClientId: '152439228985-2mjvtoq3odc63de5d90k48kb67mvscnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.thefuture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz_1G72dP1XPDcdD-f9WsTp2OWvfHITsY',
    appId: '1:152439228985:ios:99f7f71b08ccaa181d9be8',
    messagingSenderId: '152439228985',
    projectId: 'thefuture-f7945',
    storageBucket: 'thefuture-f7945.appspot.com',
    iosClientId: '152439228985-2mjvtoq3odc63de5d90k48kb67mvscnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.thefuture',
  );
}
